language: java
jdk:
  - oraclejdk8
#  - openjdk8
#  - oraclejdk9

cache:
  apt: true
  directories:
    - $HOME/.m2

sudo: required

addons:
  apt:
    packages:
      - jq

install:
  # install python env
  - sudo apt-get install software-properties-common
  - sudo apt-add-repository universe
  - sudo add-apt-repository restricted
  - sudo add-apt-repository multiverse
  - sudo apt-get update
  - sudo apt-get install python-pip
  - sudo pip install ipfsapi
  - sudo pip install flask
  - sudo pip install pyOpenSSL
  - sudo pip install pyota
  - sudo pip install docker
  - sudo pip install mock
  - sudo pip install cryptography==2.5
  - sudo pip install sh
  - sudo pip install six --upgrade
  - sudo pip install ecdsa
  # install ipfs
  - wget https://dist.ipfs.io/go-ipfs/v0.4.18/go-ipfs_v0.4.18_linux-amd64.tar.gz
    && tar xf go-ipfs_v0.4.18_linux-amd64.tar.gz
    && cd go-ipfs/
    && sudo ./install.sh
    && cd ..
  # update go version
  - gimme 1.11.5
  - source ~/.gimme/envs/go1.11.5.env

before_script:
  - ipfs init
    && ipfs daemon &> /tmp/ipfs.log &

script:
  - git clone https://github.com/triasteam/iri.git --depth 1
  - cd iri
  - git log
  - mvn clean compile &> compile.log
  - mvn package &>> compile.log
  - cd ..
  - VERSION=1.5.5
  - bash run_all_stable_tests.sh $VERSION

after_failure:
  - cat iri/compile.log
  - for (( i=1; i<=5; i++)) do if [ -d iri/node$i ] ; then echo && echo "node" $i "app.log >>>" && cat iri/node$i/app.log; echo && echo "node" $i "iota.log >>>" && cat iri/node$i/iri.log; fi; done
  - cat /tmp/ipfs.log
